export const blockGroups = {
  content: "Content · 콘텐츠",
  dashboard: "Dashboard · 대시보드",
  forms: "Forms · 입력과 설정",
  marketing: "Marketing · 소개와 안내",
} as const;
export const blocks = [
  {
    slug: "editorial-hero",
    name: "Editorial Hero",
    group: "content",
    description: "글과 제품의 첫인상을 만드는 비주얼 히어로.",
    component: "EditorialHero",
    api: "title, description, eyebrow, primary, secondary, artwork",
  },
  {
    slug: "article-grid",
    name: "Article Grid",
    group: "content",
    description: "검색과 분류 필터가 있는 반응형 글 목록.",
    component: "ArticleGrid",
    api: "articles: Article[]",
  },
  {
    slug: "featured-story",
    name: "Featured Story",
    group: "content",
    description: "큰 비주얼과 글 소개를 나란히 배치한 추천 콘텐츠.",
    component: "FeaturedStory",
    api: "article, eyebrow",
  },
  {
    slug: "reading-list",
    name: "Reading List",
    group: "content",
    description: "북마크 선택 상태를 앱 데이터와 연결하는 읽기 목록.",
    component: "ReadingList",
    api: "articles, savedIds, onSavedChange",
  },
  {
    slug: "author-profile",
    name: "Author Profile",
    group: "content",
    description: "작가 소개, 관심 주제와 활동 정보를 모은 프로필.",
    component: "AuthorProfile",
    api: "name, bio, initials, topics, stats, link, portrait",
  },
  {
    slug: "article-outline",
    name: "Article Outline",
    group: "content",
    description: "현재 위치와 읽기 진행률을 표시하는 문서 목차.",
    component: "ArticleOutline",
    api: "sections, activeId, progress",
  },
  {
    slug: "analytics-overview",
    name: "Analytics Overview",
    group: "dashboard",
    description: "핵심 지표, 방문 추이와 데이터 표를 갖춘 분석 패널.",
    component: "AnalyticsOverview",
    api: "metrics, data, series",
  },
  {
    slug: "activity-feed",
    name: "Activity Feed",
    group: "dashboard",
    description: "카테고리별로 골라 보는 작업실 활동 타임라인.",
    component: "ActivityFeed",
    api: "items",
  },
  {
    slug: "project-board",
    name: "Project Board",
    group: "dashboard",
    description: "접근 가능한 상태 선택기로 작업을 옮기는 칸반 보드.",
    component: "ProjectBoard",
    api: "columns, tasks, onTasksChange",
  },
  {
    slug: "task-panel",
    name: "Task Panel",
    group: "dashboard",
    description: "자체 체크박스와 진행률을 함께 쓰는 작업 체크리스트.",
    component: "TaskPanel",
    api: "tasks, onTasksChange",
  },
  {
    slug: "team-directory",
    name: "Team Directory",
    group: "dashboard",
    description: "이름·역할·이메일로 찾을 수 있는 팀 주소록.",
    component: "TeamDirectory",
    api: "members",
  },
  {
    slug: "command-workspace",
    name: "Command Workspace",
    group: "dashboard",
    description: "검색과 키보드 선택으로 자주 하는 작업을 실행하는 패널.",
    component: "CommandWorkspace",
    api: "commands: id, label, description, group, onSelect",
  },
  {
    slug: "sign-in",
    name: "Sign In",
    group: "forms",
    description: "검증·처리 중·오류 상태를 갖춘 로그인 폼.",
    component: "SignIn",
    api: "onSubmit, recoveryHref, successMessage",
  },
  {
    slug: "newsletter",
    name: "Newsletter",
    group: "forms",
    description: "이메일 검증과 비동기 구독 콜백을 연결하는 구독 섹션.",
    component: "Newsletter",
    api: "onSubscribe, privacyHref, successMessage",
  },
  {
    slug: "contact",
    name: "Contact",
    group: "forms",
    description: "이름·이메일·문의 내용을 검증하고 제출하는 문의 폼.",
    component: "Contact",
    api: "onSubmit, successMessage",
  },
  {
    slug: "profile-settings",
    name: "Profile Settings",
    group: "forms",
    description: "프로필 편집·초기화·저장 결과를 한 화면에 배치.",
    component: "ProfileSettings",
    api: "profile, onSave, successMessage",
  },
  {
    slug: "notification-settings",
    name: "Notification Settings",
    group: "forms",
    description: "알림 항목과 설명을 스위치로 조절하는 설정 목록.",
    component: "NotificationSettings",
    api: "preferences, onChange, onSave, successMessage",
  },
  {
    slug: "upload-panel",
    name: "Upload Panel",
    group: "forms",
    description: "파일 선택·크기 검증·제거와 업로드 콜백을 묶은 패널.",
    component: "UploadPanel",
    api: "onUpload, accept, maxFiles, maxSize, successMessage",
  },
  {
    slug: "pricing",
    name: "Pricing",
    group: "marketing",
    description: "월간·연간 금액 전환과 플랜 선택 콜백이 있는 요금표.",
    component: "Pricing",
    api: "plans, currency, locale, onSelect",
  },
  {
    slug: "faq",
    name: "FAQ",
    group: "marketing",
    description: "키보드 탐색과 부드러운 열림 모션을 갖춘 질문 목록.",
    component: "Faq",
    api: "items",
  },
  {
    slug: "testimonials",
    name: "Testimonials",
    group: "marketing",
    description: "인용문과 작성자를 읽기 쉽게 묶은 후기 카드.",
    component: "Testimonials",
    api: "items",
  },
  {
    slug: "feature-grid",
    name: "Feature Grid",
    group: "marketing",
    description: "SVG 아이콘과 핵심 기능을 배치한 반응형 특징 섹션.",
    component: "FeatureGrid",
    api: "features: id, title, description, icon, href",
  },
  {
    slug: "stats-band",
    name: "Stats Band",
    group: "marketing",
    description: "세 가지 주요 수치를 강하게 보여 주는 대비 섹션.",
    component: "StatsBand",
    api: "stats",
  },
  {
    slug: "release-notes",
    name: "Release Notes",
    group: "marketing",
    description: "버전·날짜·변경 내용을 나란히 읽는 업데이트 기록.",
    component: "ReleaseNotes",
    api: "releases",
  },
] as const;
export type BlockSlug = (typeof blocks)[number]["slug"];
