export type Group =
  "core" | "forms" | "navigation" | "overlays" | "data" | "advanced" | "chat";
export type ComponentEntry = {
  slug: string;
  name: string;
  description: string;
  group: Group;
  api: string;
  usage: string;
  source: string;
};
export const groupLabels: Record<Group, string> = {
  core: "Foundations",
  forms: "Forms & inputs",
  navigation: "Navigation",
  overlays: "Overlays & menus",
  data: "Data & layout",
  advanced: "Advanced",
  chat: "Conversation",
};
export const catalog: ComponentEntry[] = [
  {
    slug: "button",
    name: "Button",
    description: "동작과 상태를 명확하게 전달하는 버튼.",
    group: "core",
    api: "variant, size, loading, loadingLabel, disabled",
    usage: "<Button loading={pending}>변경 사항 저장</Button>",
    source: "button",
  },
  {
    slug: "button-group",
    name: "Button Group",
    description: "연관된 액션을 하나의 그룹으로 묶습니다.",
    group: "core",
    api: "children, aria-label",
    usage:
      '<ButtonGroup aria-label="파일 작업"><Button>저장</Button><Button variant="secondary">복제</Button></ButtonGroup>',
    source: "button-group",
  },
  {
    slug: "badge",
    name: "Badge",
    description: "의미 있는 색상과 작은 상태 표시.",
    group: "core",
    api: "tone, dot",
    usage: '<Badge tone="success" dot>게시됨</Badge>',
    source: "badge",
  },
  {
    slug: "card",
    name: "Card",
    description: "유연하게 조합하는 콘텐츠 표면.",
    group: "core",
    api: "CardHeader, CardTitle, CardDescription, CardContent, CardFooter",
    usage:
      "<Card><CardHeader><CardTitle>새 프로젝트</CardTitle></CardHeader><CardContent>콘텐츠</CardContent></Card>",
    source: "card",
  },
  {
    slug: "alert",
    name: "Alert",
    description: "문맥 안에 머무르는 상태 안내.",
    group: "core",
    api: "AlertTitle, AlertDescription, role",
    usage:
      "<Alert><AlertTitle>저장이 완료되었습니다</AlertTitle><AlertDescription>모든 변경 사항이 반영되었습니다.</AlertDescription></Alert>",
    source: "alert",
  },
  {
    slug: "avatar",
    name: "Avatar",
    description: "이미지를 불러오지 못해도 유지되는 사용자 표현.",
    group: "core",
    api: "AvatarImage, AvatarFallback, delayMs",
    usage: "<Avatar><AvatarFallback>DH</AvatarFallback></Avatar>",
    source: "avatar",
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio",
    description: "레이아웃 이동 없이 미디어 비율을 유지합니다.",
    group: "core",
    api: "ratio, style",
    usage: "<AspectRatio ratio={16 / 9}><div>미디어</div></AspectRatio>",
    source: "aspect-ratio",
  },
  {
    slug: "empty",
    name: "Empty",
    description: "빈 화면에도 다음 행동을 안내합니다.",
    group: "core",
    api: "title, description, icon, action",
    usage:
      '<EmptyState title="아직 글이 없습니다" description="첫 글을 작성해 보세요." action={<Button>글 쓰기</Button>} />',
    source: "empty-state",
  },
  {
    slug: "item",
    name: "Item",
    description: "아이콘, 내용, 액션으로 구성하는 목록 단위.",
    group: "core",
    api: "ItemMedia, ItemContent, ItemTitle, ItemDescription, ItemActions, ItemGroup",
    usage:
      "<Item><ItemContent><ItemTitle>프로젝트</ItemTitle></ItemContent><ItemActions><Button>열기</Button></ItemActions></Item>",
    source: "item",
  },
  {
    slug: "kbd",
    name: "Kbd",
    description: "키보드 단축키를 읽기 쉽게 표시합니다.",
    group: "core",
    api: "Kbd, KbdGroup",
    usage: "<KbdGroup><Kbd>Ctrl</Kbd><Kbd>K</Kbd></KbdGroup>",
    source: "kbd",
  },
  {
    slug: "marker",
    name: "Marker",
    description: "문장에서 중요한 정보를 강조합니다.",
    group: "core",
    api: "children",
    usage: "<Marker>중요한 단어</Marker>",
    source: "marker",
  },
  {
    slug: "separator",
    name: "Separator",
    description: "장식 또는 의미 있는 구분선을 배치합니다.",
    group: "core",
    api: "orientation, decorative",
    usage: "<Separator decorative={false} />",
    source: "separator",
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    description: "콘텐츠의 크기를 유지하는 로딩 자리 표시.",
    group: "core",
    api: "style, className, aria-hidden",
    usage: "<Skeleton style={{ width: 240, height: 20 }} />",
    source: "skeleton",
  },
  {
    slug: "spinner",
    name: "Spinner",
    description: "보조 기술에 로딩 상태를 알립니다.",
    group: "core",
    api: "label",
    usage: '<Spinner label="콘텐츠 불러오는 중" />',
    source: "spinner",
  },
  {
    slug: "progress",
    name: "Progress",
    description: "진행률을 부드럽고 정확하게 전달합니다.",
    group: "core",
    api: "value, label",
    usage: '<Progress value={64} label="업로드 진행률" />',
    source: "progress",
  },
  {
    slug: "typography",
    name: "Typography",
    description: "제목부터 인용까지 일관된 타이포그래피.",
    group: "core",
    api: "Heading, Text, Code, Blockquote",
    usage: "<Heading>읽기 좋은 인터페이스</Heading>",
    source: "typography",
  },
  {
    slug: "input",
    name: "Input",
    description: "네이티브 입력 의미를 유지하는 텍스트 필드.",
    group: "forms",
    api: "type, disabled, required, aria-invalid, ref",
    usage:
      '<Input aria-label="이메일" type="email" placeholder="you@example.com" />',
    source: "input",
  },
  {
    slug: "field",
    name: "Field",
    description: "레이블, 설명, 오류 메시지의 일관된 연결.",
    group: "forms",
    api: "label, htmlFor, description, error, required",
    usage:
      '<Field label="이메일" htmlFor="email" description="업무용 주소를 입력하세요"><Input id="email" aria-describedby="email-hint" /></Field>',
    source: "input",
  },
  {
    slug: "label",
    name: "Label",
    description: "입력 요소에 이름을 연결합니다.",
    group: "forms",
    api: "htmlFor",
    usage: '<Label htmlFor="name">이름</Label>',
    source: "label",
  },
  {
    slug: "textarea",
    name: "Textarea",
    description: "여러 줄 텍스트를 작성합니다.",
    group: "forms",
    api: "rows, maxLength, disabled, aria-invalid",
    usage: '<Textarea aria-label="소개" placeholder="짧게 소개해 주세요" />',
    source: "input",
  },
  {
    slug: "input-group",
    name: "Input Group",
    description: "접두사, 접미사, 입력을 하나로 조합합니다.",
    group: "forms",
    api: "InputGroupAddon, InputGroupText, children",
    usage:
      '<InputGroup><InputGroupAddon>https://</InputGroupAddon><Input aria-label="도메인" /></InputGroup>',
    source: "input-group",
  },
  {
    slug: "input-otp",
    name: "Input OTP",
    description: "붙여넣기와 자동 완성을 지원하는 인증 코드.",
    group: "forms",
    api: "maxLength, value, onChange, onComplete, pattern, disabled",
    usage: '<InputOTP aria-label="인증 코드" maxLength={6} />',
    source: "input-otp",
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    description: "선택과 부분 선택을 표현합니다.",
    group: "forms",
    api: "checked, defaultChecked, onCheckedChange, disabled, name",
    usage: '<Checkbox aria-label="약관 동의" />',
    source: "checkbox",
  },
  {
    slug: "radio-group",
    name: "Radio Group",
    description: "여러 옵션 중 하나를 키보드로 선택합니다.",
    group: "forms",
    api: "value, onValueChange, orientation, RadioGroupItem",
    usage:
      '<RadioGroup aria-label="요금제" defaultValue="free"><RadioGroupItem value="free" aria-label="무료" /><RadioGroupItem value="pro" aria-label="프로" /></RadioGroup>',
    source: "radio-group",
  },
  {
    slug: "switch",
    name: "Switch",
    description: "설정을 즉시 켜고 끕니다.",
    group: "forms",
    api: "checked, defaultChecked, onCheckedChange, disabled, name",
    usage: '<Switch aria-label="알림 받기" defaultChecked />',
    source: "switch",
  },
  {
    slug: "slider",
    name: "Slider",
    description: "하나 또는 여러 값을 드래그·키보드로 조절합니다.",
    group: "forms",
    api: "value, defaultValue, onValueChange, min, max, step, thumbLabels",
    usage: '<Slider defaultValue={[25, 75]} thumbLabels={["최소", "최대"]} />',
    source: "slider",
  },
  {
    slug: "select",
    name: "Select",
    description: "검색 문자와 방향키를 지원하는 옵션 선택.",
    group: "forms",
    api: "SelectTrigger, SelectValue, SelectContent, SelectItem, value, onValueChange",
    usage:
      '<Select defaultValue="ko"><SelectTrigger aria-label="언어"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ko">한국어</SelectItem></SelectContent></Select>',
    source: "select",
  },
  {
    slug: "native-select",
    name: "Native Select",
    description: "운영체제의 기본 선택 경험을 유지합니다.",
    group: "forms",
    api: "value, onChange, multiple, disabled, name",
    usage:
      '<NativeSelect aria-label="언어"><NativeSelectOption value="ko">한국어</NativeSelectOption></NativeSelect>',
    source: "native-select",
  },
  {
    slug: "combobox",
    name: "Combobox",
    description: "텍스트로 검색하고 키보드로 선택합니다.",
    group: "forms",
    api: "options, value, onValueChange, label, disabled, emptyLabel",
    usage:
      '<Combobox label="프레임워크" options={[{ value: "next", label: "Next.js" }]} value={value} onValueChange={setValue} />',
    source: "combobox",
  },
  {
    slug: "toggle",
    name: "Toggle",
    description: "툴바의 이진 선택 상태.",
    group: "forms",
    api: "pressed, onPressedChange, disabled",
    usage: '<Toggle aria-label="굵게">B</Toggle>',
    source: "toggle",
  },
  {
    slug: "toggle-group",
    name: "Toggle Group",
    description: "단일 또는 다중 선택을 묶습니다.",
    group: "forms",
    api: "type, value, onValueChange, ToggleGroupItem",
    usage:
      '<ToggleGroup type="single" aria-label="정렬"><ToggleGroupItem value="left" aria-label="왼쪽">←</ToggleGroupItem></ToggleGroup>',
    source: "toggle-group",
  },
  {
    slug: "submit-button",
    name: "Submit Button",
    description: "React 폼의 제출 상태를 자동으로 반영합니다.",
    group: "forms",
    api: "loadingLabel, disabled, variant, form action context",
    usage: "<form action={save}><SubmitButton>저장</SubmitButton></form>",
    source: "submit-button",
  },
  {
    slug: "accordion",
    name: "Accordion",
    description: "높이 애니메이션으로 내용이 자연스럽게 펼쳐집니다.",
    group: "navigation",
    api: "type, collapsible, value, onValueChange, AccordionItem, AccordionTrigger, AccordionContent",
    usage:
      '<Accordion type="single" collapsible><AccordionItem value="one"><AccordionTrigger>사용 방법</AccordionTrigger><AccordionContent>프로젝트에서 가져와 사용하세요.</AccordionContent></AccordionItem></Accordion>',
    source: "accordion",
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    description: "현재 위치와 상위 경로를 표시합니다.",
    group: "navigation",
    api: "BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage",
    usage:
      '<Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href="/">홈</BreadcrumbLink></BreadcrumbItem><BreadcrumbItem><BreadcrumbPage>컴포넌트</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb>',
    source: "breadcrumb",
  },
  {
    slug: "tabs",
    name: "Tabs",
    description: "활성 표시가 움직이는 키보드 탐색 탭.",
    group: "navigation",
    api: "value, defaultValue, onValueChange, orientation, activationMode, TabsList, TabsTrigger, TabsContent",
    usage:
      '<Tabs defaultValue="preview"><TabsList aria-label="보기"><TabsTrigger value="preview">미리보기</TabsTrigger><TabsTrigger value="code">코드</TabsTrigger></TabsList><TabsContent value="preview">컴포넌트</TabsContent><TabsContent value="code">소스 코드</TabsContent></Tabs>',
    source: "tabs",
  },
  {
    slug: "collapsible",
    name: "Collapsible",
    description: "선택적인 정보를 펼치고 접습니다.",
    group: "navigation",
    api: "open, onOpenChange, CollapsibleTrigger, CollapsibleContent",
    usage:
      "<Collapsible><CollapsibleTrigger asChild><Button>자세히</Button></CollapsibleTrigger><CollapsibleContent>추가 정보</CollapsibleContent></Collapsible>",
    source: "collapsible",
  },
  {
    slug: "navigation-menu",
    name: "Navigation Menu",
    description: "키보드 탐색과 콘텐츠 패널을 갖춘 내비게이션.",
    group: "navigation",
    api: "NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink",
    usage:
      '<NavigationMenu><NavigationMenuList><NavigationMenuItem><NavigationMenuLink href="/">홈</NavigationMenuLink></NavigationMenuItem></NavigationMenuList></NavigationMenu>',
    source: "navigation-menu",
  },
  {
    slug: "pagination",
    name: "Pagination",
    description: "현재 페이지와 이전·다음 이동.",
    group: "navigation",
    api: "page, pageCount, onPageChange",
    usage: "<Pagination page={page} pageCount={5} onPageChange={setPage} />",
    source: "pagination",
  },
  {
    slug: "sidebar",
    name: "Sidebar",
    description: "접을 수 있는 사이드 탐색 레이아웃.",
    group: "navigation",
    api: "SidebarProvider, SidebarTrigger, SidebarContent, SidebarInset, SidebarGroup, SidebarMenuButton",
    usage:
      "<SidebarProvider><Sidebar><SidebarContent>메뉴</SidebarContent></Sidebar><SidebarInset><SidebarTrigger />본문</SidebarInset></SidebarProvider>",
    source: "sidebar",
  },
  {
    slug: "nav-link",
    name: "Nav Link",
    description: "Next.js 경로와 연결되는 활성 링크.",
    group: "navigation",
    api: "href, exact, prefetch, replace, aria-current",
    usage: '<NavLink href="/components/button">Button</NavLink>',
    source: "nav-link",
  },
  {
    slug: "direction",
    name: "Direction",
    description: "양방향 텍스트와 키보드 탐색 방향.",
    group: "navigation",
    api: "dir, children",
    usage:
      '<DirectionProvider dir="rtl"><div dir="rtl">오른쪽에서 왼쪽으로</div></DirectionProvider>',
    source: "direction",
  },
  {
    slug: "dialog",
    name: "Dialog",
    description: "포커스를 관리하고 Escape로 닫히는 모달.",
    group: "overlays",
    api: "open, onOpenChange, DialogTrigger, DialogContent, DialogTitle, DialogDescription, DialogClose",
    usage:
      "<Dialog><DialogTrigger asChild><Button>열기</Button></DialogTrigger><DialogContent><DialogTitle>설정</DialogTitle><DialogDescription>환경을 변경하세요.</DialogDescription></DialogContent></Dialog>",
    source: "dialog",
  },
  {
    slug: "alert-dialog",
    name: "Alert Dialog",
    description: "중요한 결정을 명시적인 액션으로 확인합니다.",
    group: "overlays",
    api: "AlertDialogTrigger, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel",
    usage:
      '<AlertDialog><AlertDialogTrigger asChild><Button>확인</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>계속할까요?</AlertDialogTitle><AlertDialogDescription>설정을 적용합니다.</AlertDialogDescription><AlertDialogCancel asChild><Button variant="outline">취소</Button></AlertDialogCancel><AlertDialogAction asChild><Button>적용</Button></AlertDialogAction></AlertDialogContent></AlertDialog>',
    source: "alert-dialog",
  },
  {
    slug: "sheet",
    name: "Sheet",
    description: "화면 가장자리에서 여는 보조 작업 공간.",
    group: "overlays",
    api: "side, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose",
    usage:
      "<Sheet><SheetTrigger asChild><Button>열기</Button></SheetTrigger><SheetContent><SheetTitle>상세 설정</SheetTitle><SheetDescription>선택한 항목의 설정입니다.</SheetDescription></SheetContent></Sheet>",
    source: "sheet",
  },
  {
    slug: "drawer",
    name: "Drawer",
    description: "터치 드래그로 조작하는 서랍형 패널.",
    group: "overlays",
    api: "direction, snapPoints, open, onOpenChange, DrawerContent, DrawerTitle, DrawerDescription, DrawerClose",
    usage:
      "<Drawer><DrawerTrigger asChild><Button>열기</Button></DrawerTrigger><DrawerContent><DrawerTitle>빠른 설정</DrawerTitle><DrawerDescription>아래로 밀어 닫을 수 있습니다.</DrawerDescription></DrawerContent></Drawer>",
    source: "drawer",
  },
  {
    slug: "popover",
    name: "Popover",
    description: "주변 문맥을 유지하는 작은 작업 패널.",
    group: "overlays",
    api: "open, modal, PopoverTrigger, PopoverContent, PopoverClose, side, align",
    usage:
      "<Popover><PopoverTrigger asChild><Button>설정</Button></PopoverTrigger><PopoverContent>빠른 설정</PopoverContent></Popover>",
    source: "popover",
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    description: "포인터와 키보드 포커스로 보이는 짧은 설명.",
    group: "overlays",
    api: "TooltipProvider, delayDuration, TooltipTrigger, TooltipContent, side",
    usage:
      "<TooltipProvider><Tooltip><TooltipTrigger asChild><Button>저장</Button></TooltipTrigger><TooltipContent>변경 사항을 저장합니다</TooltipContent></Tooltip></TooltipProvider>",
    source: "tooltip",
  },
  {
    slug: "hover-card",
    name: "Hover Card",
    description: "링크를 따라가기 전에 내용을 미리 봅니다.",
    group: "overlays",
    api: "openDelay, closeDelay, HoverCardTrigger, HoverCardContent",
    usage:
      '<HoverCard><HoverCardTrigger href="#profile">프로필</HoverCardTrigger><HoverCardContent>작성자 소개</HoverCardContent></HoverCard>',
    source: "hover-card",
  },
  {
    slug: "dropdown-menu",
    name: "Dropdown Menu",
    description: "하위 메뉴·체크 항목·라디오 선택 메뉴.",
    group: "overlays",
    api: "DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioItem, DropdownMenuSub",
    usage:
      "<DropdownMenu><DropdownMenuTrigger asChild><Button>메뉴</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>편집</DropdownMenuItem></DropdownMenuContent></DropdownMenu>",
    source: "dropdown-menu",
  },
  {
    slug: "context-menu",
    name: "Context Menu",
    description: "우클릭·길게 누르기·키보드로 여는 메뉴.",
    group: "overlays",
    api: "ContextMenuTrigger, ContextMenuContent, ContextMenuItem, ContextMenuSub",
    usage:
      "<ContextMenu><ContextMenuTrigger>우클릭</ContextMenuTrigger><ContextMenuContent><ContextMenuItem>복사</ContextMenuItem></ContextMenuContent></ContextMenu>",
    source: "context-menu",
  },
  {
    slug: "menubar",
    name: "Menubar",
    description: "데스크톱 앱과 같은 다중 메뉴 탐색.",
    group: "overlays",
    api: "MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem, MenubarSub",
    usage:
      "<Menubar><MenubarMenu><MenubarTrigger>파일</MenubarTrigger><MenubarContent><MenubarItem>새로 만들기</MenubarItem></MenubarContent></MenubarMenu></Menubar>",
    source: "menubar",
  },
  {
    slug: "command",
    name: "Command",
    description: "검색과 키보드 조작을 갖춘 명령 목록.",
    group: "overlays",
    api: "CommandInput, CommandList, CommandItem, CommandGroup, CommandEmpty, onSelect",
    usage:
      '<Command label="명령"><CommandInput placeholder="검색"/><CommandList><CommandEmpty>결과 없음</CommandEmpty><CommandItem onSelect={openSettings}>설정</CommandItem></CommandList></Command>',
    source: "command",
  },
  {
    slug: "toast",
    name: "Toast",
    description: "액션과 비동기 상태를 지원하는 알림.",
    group: "overlays",
    api: "Toaster, toast, toast.success, toast.error, toast.promise, action",
    usage:
      '<><Button onClick={() => toast.success("저장되었습니다")}>저장</Button><Toaster /></>',
    source: "toast",
  },
  {
    slug: "calendar",
    name: "Calendar",
    description: "단일·다중·기간 선택과 로케일을 지원합니다.",
    group: "data",
    api: "mode, selected, onSelect, disabled, locale, numberOfMonths, timeZone",
    usage: '<Calendar mode="range" selected={range} onSelect={setRange} />',
    source: "calendar",
  },
  {
    slug: "date-picker",
    name: "Date Picker",
    description: "팝오버 달력과 선택한 날짜 표시.",
    group: "data",
    api: "value, onValueChange, label, disabled, locale, calendarProps",
    usage: '<DatePicker label="게시일" value={date} onValueChange={setDate} />',
    source: "date-picker",
  },
  {
    slug: "table",
    name: "Table",
    description: "의미 있는 HTML 구조의 데이터 표.",
    group: "data",
    api: "TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell, TableCaption",
    usage:
      "<Table><TableHeader><TableRow><TableHead>이름</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>NINE</TableCell></TableRow></TableBody></Table>",
    source: "table",
  },
  {
    slug: "data-table",
    name: "Data Table",
    description: "검색·정렬·페이지·행 선택·열 표시를 통합합니다.",
    group: "data",
    api: "data, columns, label, pageSize, searchable, selectable, getRowId, onSelectionChange",
    usage:
      '<DataTable label="게시물" data={posts} columns={columns} selectable getRowId={row => row.id} />',
    source: "data-table",
  },
  {
    slug: "chart",
    name: "Chart",
    description: "Area·Bar·Line·Pie·Radar 등 조합 가능한 차트.",
    group: "data",
    api: "ChartContainer, config, label, ChartTooltip, ChartLegend, Recharts primitives",
    usage:
      '<ChartContainer label="방문 통계" config={{ visitors: { label: "방문자", color: "#3659e3" } }}><BarChart data={data}><Bar dataKey="visitors" fill="var(--color-visitors)" isAnimationActive={false} /></BarChart></ChartContainer>',
    source: "chart",
  },
  {
    slug: "carousel",
    name: "Carousel",
    description: "터치와 버튼으로 탐색하는 슬라이드.",
    group: "data",
    api: "slides, label, loop",
    usage:
      '<Carousel label="미리보기" slides={[<div key="a">첫 번째</div>, <div key="b">두 번째</div>]} />',
    source: "carousel",
  },
  {
    slug: "scroll-area",
    name: "Scroll Area",
    description: "네이티브 스크롤과 조화로운 스크롤바.",
    group: "data",
    api: "ScrollAreaViewport, ScrollAreaScrollbar, ScrollAreaThumb, type",
    usage:
      "<ScrollArea style={{ height: 160 }}><ScrollAreaViewport>긴 콘텐츠</ScrollAreaViewport><ScrollAreaScrollbar><ScrollAreaThumb /></ScrollAreaScrollbar></ScrollArea>",
    source: "scroll-area",
  },
  {
    slug: "resizable",
    name: "Resizable",
    description: "키보드·포인터로 크기를 바꾸는 패널.",
    group: "data",
    api: "ResizablePanelGroup, ResizablePanel, ResizableHandle, orientation, minSize",
    usage:
      '<ResizablePanelGroup orientation="horizontal"><ResizablePanel>탐색</ResizablePanel><ResizableHandle /><ResizablePanel>콘텐츠</ResizablePanel></ResizablePanelGroup>',
    source: "resizable",
  },
  {
    slug: "file-upload",
    name: "File Upload",
    description: "개수·크기·형식 검증을 갖춘 파일 선택.",
    group: "advanced",
    api: "value, onValueChange, accept, maxFiles, maxSize, disabled",
    usage:
      '<FileUpload value={files} onValueChange={setFiles} accept="image/*" />',
    source: "file-upload",
  },
  {
    slug: "tree",
    name: "Tree",
    description: "방향키·문자 검색·펼치기를 지원하는 트리.",
    group: "advanced",
    api: "nodes, label, value, onValueChange, defaultExpanded",
    usage:
      '<Tree label="파일" nodes={nodes} value={selected} onValueChange={setSelected} />',
    source: "tree",
  },
  {
    slug: "sortable",
    name: "Sortable",
    description: "포인터와 키보드로 순서를 바꿉니다.",
    group: "advanced",
    api: "items, onValueChange, label",
    usage:
      '<Sortable label="블록 순서" items={items} onValueChange={setItems} />',
    source: "sortable",
  },
  {
    slug: "attachment",
    name: "Attachment",
    description: "대화와 문서의 첨부 파일 링크.",
    group: "chat",
    api: "name, size, href, download",
    usage: '<Attachment name="안내 문서" size="PDF" href="/guide.pdf" />',
    source: "attachment",
  },
  {
    slug: "bubble",
    name: "Bubble",
    description: "발화 주체를 구분하는 메시지 표면.",
    group: "chat",
    api: "from, children",
    usage: '<Bubble from="user">안녕하세요.</Bubble>',
    source: "bubble",
  },
  {
    slug: "message",
    name: "Message",
    description: "메시지 본문과 액션의 구성 요소.",
    group: "chat",
    api: "from, MessageContent, MessageActions",
    usage:
      '<Message from="assistant"><MessageContent>어떻게 도와드릴까요?</MessageContent></Message>',
    source: "message",
  },
  {
    slug: "message-scroller",
    name: "Message Scroller",
    description: "읽는 위치를 보존하며 최신 메시지를 따라갑니다.",
    group: "chat",
    api: "label, children, className",
    usage:
      '<MessageScroller label="대화">{messages.map(message => <Message key={message.id}>{message.text}</Message>)}</MessageScroller>',
    source: "message-scroller",
  },
  {
    slug: "questionnaire",
    name: "Questionnaire",
    description: "검증·제출 상태·오류 처리가 있는 질문 폼.",
    group: "chat",
    api: "questions, onSubmit, submitLabel, disabled",
    usage:
      '<Questionnaire questions={[{id:"email",label:"이메일",type:"email",required:true}]} onSubmit={saveAnswers} />',
    source: "questionnaire",
  },
];
export const groupOrder = Object.keys(groupLabels) as Group[];
